export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const SEARCH_NAME = "SEARCH_NAME";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
// export const POST_ACTIVITIES = "POST_ACTIVITIES";